# -*- coding: utf-8 -*-
"""iris-flower-classification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OA-zJyy0eU1vUZq_x6qejoq64akF4LX6
"""

import pandas as pd     #importing libraries
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn.metrics import accuracy_score
import matplotlib.pyplot as plt

iris = load_iris()

X = iris.data   # Features (measurements)
y = iris.target # Target (species)

# Convert to DataFrame for better readability
df = pd.DataFrame(X, columns=iris.feature_names)
df['species'] = y
print(df.head())

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)  #splitting test and train tests

model = DecisionTreeClassifier(random_state=42)
model.fit(X_train, y_train)       #training model on the train set

y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print("Model Accuracy:", accuracy)

plt.figure(figsize=(12,8))
plot_tree(model, feature_names=iris.feature_names,class_names=iris.target_names,filled=True)
plt.show()

sample = np.array([[5.1, 3.5, 1.4, 0.2]])  # Example flower
pred = model.predict(sample)
print("Predicted Species:", iris.target_names[pred][0])